### ISSUE TITLE
執行範例程式 TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by jacklin1218** [SsallyLin/touchprice#10]
環境如下
python:3.8.16
shioaji:1.1.2 
touchprice:0.1.5
OS:windows10

您好 我照著範例程式執行

touch_cmd = tp.TouchCmd(
        code="2890", 
        close = tp.Price(price=10.0, trend="Up")
    )
order_cmd = tp.OrderCmd(
    code="2890",
    order = sj.Order(
        action="Buy",
        price=10,
        quantity=1,
        order_type="ROD",
        price_type="LMT",)
    )

condition = tp.TouchOrderCond(
                touch_cmd = touch_cmd, 
                order_cmd = order_cmd
            )
touch.add_condition(condition)

會出現錯誤
Cell In[4], line 19
      5 order_cmd = tp.OrderCmd(
      6     code="2890",
      7     order = sj.Order(
   (...)
     12         price_type="LMT",)
     13     )
     15 condition = tp.TouchOrderCond(
     16                 touch_cmd = touch_cmd, 
     17                 order_cmd = order_cmd
     18             )
---> 19 touch.add_condition(condition)

File [d:\anaconda3\envs\FinLab\lib\site-packages\touchprice\touch_price.py:84](file:///D:/anaconda3/envs/FinLab/lib/site-packages/touchprice/touch_price.py:84), in TouchOrderExecutor.add_condition(self, condition)
     82 touch_contract = self.contracts[code]
     83 self.update_snapshot(touch_contract)
---> 84 store_condition = self.adjust_condition(condition, touch_contract)
     85 if store_condition:
     86     if code in self.conditions.keys():

File [d:\anaconda3\envs\FinLab\lib\site-packages\touchprice\touch_price.py:65](file:///D:/anaconda3/envs/FinLab/lib/site-packages/touchprice/touch_price.py:65), in TouchOrderExecutor.adjust_condition(self, condition, contract)
     62 def adjust_condition(
     63     self, condition: TouchOrderCond, contract: sj.contracts.Contract
...
     67     }
     68     if tconds_dict:
     69         for key, value in tconds_dict.items():

TypeError: 'NoneType' object is not iterable

請問該如何解決

**Comment by jacklin1218** [comment]
我把 condition.touch_cmd的內容print出來的結果是

code 2890
close price=10.0 trend=<Trend.Up: 'Up'> price_type=<PriceType.LimitPrice: 'LimitPrice'>
buy_price None
sell_price None
high None
low None
volume None
total_volume None
ask_volume None
bid_volume None

**Comment by SsallyLin** [comment]
pydantic的版本為多少?

**Comment by jacklin1218** [comment]
pydantic 1.10.7

**Comment by SsallyLin** [comment]
pydantic的版本降到1.0可解決此問題
