### ISSUE TITLE
'touchprice' has no attribute 'TouchOrderExecutor' (most likely due to a circular import)

### ISSUE THREAD

**Issue by yaoshihyu2023** [SsallyLin/touchprice#11]
```
import touchprice as tp
import shioaji as sj

api = sj.Shioaji()
api.login("YOUR_API_KEY", "YOUR_SECRET_KEY")
api.activate_ca(CA_PATH, CA_USERID, CA_PASSWORD)
touch = tp.TouchOrderExecutor(api)
```

使用上面程式碼出現下面錯誤 ～ 想請問一下原因  謝謝

AttributeError: partially initialized module 'touchprice' has no attribute 'TouchOrderExecutor' (most likely due to a circular import)

**Comment by SsallyLin** [comment]
"most likely due to a circular import"<-這部分感覺是操作上的錯誤，不是套件本身的問題
你是不是把touchprice當檔名之類的?

**Comment by yaoshihyu2023** [comment]
的確是我問題～ 檔名一樣～
