### ISSUE TITLE
KeyError when call function of add_condition

### ISSUE THREAD

**Issue by arthur55** [SsallyLin/touchprice#6]
您好，  
我照著本專案 tutor 裡的程式碼執行，  
在 `add_condition` 這個 function 出現 KeyError，  
請問有什麼方法可以解決嗎？謝謝  
![image](https://user-images.githubusercontent.com/8954015/90994682-1bd1d380-e5ec-11ea-98ed-18fc23eb4af2.png)

**Comment by SsallyLin** [comment]
您好
Touchprice 內使用 Shioaji 的 contract
此錯誤為 Touchprice 使用時 Shioaji contract 尚未下載完畢
可利用 api.Contracts.Stocks["2890"] 是否有顯示商品資訊來檢查是否下載完成
謝謝

**Comment by arthur55** [comment]
![image](https://user-images.githubusercontent.com/8954015/91181802-f3e18d80-e71b-11ea-819c-339367ecc12a.png)  
`api.Contracts.Stocks["2890"]` 執行沒有問題，謝謝

**Comment by SsallyLin** [comment]
在 touch = tp.TouchOrder(api) 之前確認 api.Contracts.Stocks["2890"]

**Comment by arthur55** [comment]
感謝，重新執行後又可以了
