### ISSUE TITLE
ubuntu 安裝後導致無法 import shioaji

### ISSUE THREAD

**Issue by ychuangab** [SsallyLin/touchprice#7]
![2021-02-09_15-24](https://user-images.githubusercontent.com/33317054/107329346-fd548b80-6aea-11eb-9bc9-2e69938fc341.png)

ubuntu 安裝後導致無法 import shioaji
系統報錯如圖
研判應該是有在相對應的 __init__.py 有加入下面這兩行 for windows的路徑修正
linux based os 應該用不到才對？

    if sys.version_info.major == 3 and sys.version_info.minor >= 8:
        os.add_dll_directory(libs_path.as_posix())

目前把報錯的兩個 __init__.py 的上兩行註解掉可以正常登入
但不知道後續是否會有其他問題
/lib/python3.8/site-packages/pysolace/__init__.py
/lib/python3.8/site-packages/shioaji/__init__.py

**Comment by SsallyLin** [comment]
因shioaji版本過舊，已更新謝謝
