### ISSUE TITLE
說明檔錯誤百出

### ISSUE THREAD

**Issue by gemini-mouse** [SsallyLin/touchprice#8]
真心建議作者將自己說明檔的程式碼複製到空的文本，然後執行看看。
錯誤實在太多，根本無法執行，我以下僅簡單舉出兩個錯誤，實際上錯更多，請自行檢查...

1. 函式已改
tp.TouchOrder(api)   (錯誤)
tp.TouchOrderExecutor(api)        (正確)

2. 少括號
order_cmd = tp.OrderCmd(
    code="2890",
    order = sj.Order(
        action="Buy",
        price=10,
        quantity=1,
        order_type="ROD",
        price_type="LMT",
    )
)

**Comment by SsallyLin** [comment]
謝謝你的建議，已作修正。
